// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApcAaF9XteRCFcxb4giKmGxYkYDp38tP4',
    appId: '1:827528856030:web:c76e1ab565e65d451a1d4f',
    messagingSenderId: '827528856030',
    projectId: 'libraryproject10-2f3aa',
    authDomain: 'libraryproject10-2f3aa.firebaseapp.com',
    storageBucket: 'libraryproject10-2f3aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz1LUtJvlDsYEftOrkYbJ683_wy270eSs',
    appId: '1:827528856030:android:b7bec5ff6164fb011a1d4f',
    messagingSenderId: '827528856030',
    projectId: 'libraryproject10-2f3aa',
    storageBucket: 'libraryproject10-2f3aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC71eEWiLW9WPk1S-Qoj9SRlvyO6c0G3Hk',
    appId: '1:827528856030:ios:50ef7484dbaf75a81a1d4f',
    messagingSenderId: '827528856030',
    projectId: 'libraryproject10-2f3aa',
    storageBucket: 'libraryproject10-2f3aa.appspot.com',
    androidClientId: '827528856030-4eu2uih2o40jqdtqq5mq0l4k9tm0vj7n.apps.googleusercontent.com',
    iosClientId: '827528856030-lp7mlv6j1ckn1ao3u0nj94guks9o5sgo.apps.googleusercontent.com',
    iosBundleId: 'com.shelfSwap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC71eEWiLW9WPk1S-Qoj9SRlvyO6c0G3Hk',
    appId: '1:827528856030:ios:50ef7484dbaf75a81a1d4f',
    messagingSenderId: '827528856030',
    projectId: 'libraryproject10-2f3aa',
    storageBucket: 'libraryproject10-2f3aa.appspot.com',
    androidClientId: '827528856030-4eu2uih2o40jqdtqq5mq0l4k9tm0vj7n.apps.googleusercontent.com',
    iosClientId: '827528856030-lp7mlv6j1ckn1ao3u0nj94guks9o5sgo.apps.googleusercontent.com',
    iosBundleId: 'com.shelfSwap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApcAaF9XteRCFcxb4giKmGxYkYDp38tP4',
    appId: '1:827528856030:web:cf5d090fce3e1c221a1d4f',
    messagingSenderId: '827528856030',
    projectId: 'libraryproject10-2f3aa',
    authDomain: 'libraryproject10-2f3aa.firebaseapp.com',
    storageBucket: 'libraryproject10-2f3aa.appspot.com',
  );
}
