// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz1LUtJvlDsYEftOrkYbJ683_wy270eSs',
    appId: '1:827528856030:android:26212437361b35791a1d4f',
    messagingSenderId: '827528856030',
    projectId: 'libraryproject10-2f3aa',
    databaseURL: 'https://libraryproject10-2f3aa-default-rtdb.firebaseio.com',
    storageBucket: 'libraryproject10-2f3aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC71eEWiLW9WPk1S-Qoj9SRlvyO6c0G3Hk',
    appId: '1:827528856030:ios:4a8b617f459772f41a1d4f',
    messagingSenderId: '827528856030',
    projectId: 'libraryproject10-2f3aa',
    databaseURL: 'https://libraryproject10-2f3aa-default-rtdb.firebaseio.com',
    storageBucket: 'libraryproject10-2f3aa.appspot.com',
    androidClientId: '827528856030-4eu2uih2o40jqdtqq5mq0l4k9tm0vj7n.apps.googleusercontent.com',
    iosClientId: '827528856030-3ba3vn62qtuu58n6ri4i3v4p23u75v4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.libraryproject',
  );
}
