name: library_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  firebase_core : ^3.6.0
  firebase_database: ^11.1.4
  http: any
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  internet_connection_checker_plus: ^2.6.0
  camera: ^0.11.0+2
  google_mlkit_barcode_scanning: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/