name: shelfswap
description: "A Flutter project."
publish_to: 'none'
version: 0.1.0+2 # for every appbundle that you build this + number is the version code it needs to be incremented each time

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  camera: ^0.11.0+2
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.1
  firebase_core : ^3.6.0
  firebase_database: ^11.1.4
  firebase_storage: ^12.3.4
  google_mlkit_barcode_scanning: ^0.13.0
  google_sign_in: ^6.2.1
  http: any
  image_picker: ^1.1.2
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  uuid: ^4.5.1
  cached_network_image: ^3.4.1
  flutter_dotenv: ^5.2.1
  iconsax_plus: ^1.0.0
  connectivity_plus: ^6.1.2
  file_picker: ^8.3.5
  csv: ^6.0.0 # used for parsing goodreads csv imports
  flutter_native_splash: 2.4.4 # do not update this unless you update flutter (you dont want to update flutter)
  url_launcher: ^6.3.1

dependency_overrides:
  camera_android_camerax: 0.6.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
